Модуль 4, задание 5. Учебный проект
htmlacademy-nodejs/774231-buy-and-sell-3 pull request #11
Opened 2021-01-15 12:51 UTC by AleksanrdKaradzikov

2021-01-17 14:34 UTC, LordotU requested changes

2021-01-17 14:34 UTC, LordotU commented on src/express/http-service/index.js
> +class HttpApi {
Это, скорее, библиотечный класс, который может быть использован различными сервисами, поэтому в этом модуле ему не совсем место - лучше переместить куда-нибудь в `lib`

2021-01-17 14:34 UTC, LordotU commented on src/express/routes/offers/index.js
> +  res.render(`new-ticket`, {formData: {}});
Кажется, тут не будет выполнено условие из ДЗ `Форма должна быть заполнена введёнными данными.`

2021-01-17 18:59 UTC, AleksanrdKaradzikov commented on src/express/routes/offers/index.js
> +  res.render(`new-ticket`, {formData: {}});
Исправил

2021-01-22 12:31 UTC, LordotU approved these changes

2021-01-22 12:31 UTC, merged